name: asha_mitra_flutter
description: "ASHA Mitra - Community Health Worker App with Bengali/English support"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core UI & Navigation
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  go_router: ^14.7.1
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Supabase & Database
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  drift: ^2.14.1
  drift_flutter: ^0.1.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # Speech Recognition & Audio
  speech_to_text: ^7.0.0
  permission_handler: ^11.2.0
  avatar_glow: ^3.0.1
  
  # Network & Connectivity
  connectivity_plus: ^5.0.2
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage & Preferences
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Date & Time
  intl: ^0.20.2
  
  # Utils & Helpers
  uuid: ^4.3.3
  crypto: ^3.0.3
  
  # UI Components
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Charts & Analytics
  fl_chart: ^0.66.2
  
  # Form Validation
  form_validator: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/audio/
    - .env
    
  # Custom fonts will be added when font files are available
  # fonts:
  #   - family: Bengali
  #     fonts:
  #       - asset: assets/fonts/NotoSansBengali-Regular.ttf
  #       - asset: assets/fonts/NotoSansBengali-Bold.ttf
  #         weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
